name: Test Project
on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths-ignore:
      - .github/workflows/*
jobs:
  test:
    runs-on: ubuntu-slim
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6
      - name: Install Dependencies
        run: npm ci
      - name: Run Tests
        run: npm test
  build:
    needs: test
    runs-on: ubuntu-slim
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6
      - name: Install Dependencies
        run: npm ci
      - name: Build Project
        run: npm run build
      - name: Publish JS Filename
        run: find dist/assets/*.js -type f -execdir echo '{}' ';'
      - name: Upload Artifacts
        uses: actions/upload-artifact@v7
        with:
          name: dist-files
          path: dist
  deploy:
    needs: build
    runs-on: ubuntu-slim
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v8
        with:
          name: dist-files
      - name: Display Contents
        run: ls -la
      - name: Deploy
        run: echo 'Deploying...'