name: Matrix Demo
on: push
jobs:
  build:
    strategy:
      matrix:
        runner-os: [ubuntu-slim, windows-latest]
    runs-on: ${{ matrix.runner-os }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6
      - name: Install Dependencies
        run: npm ci
      - name: Build Project
        run: npm run build